[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["demo/**"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[service]
rootDirectory = "demo"
